spring:
  cloud:
    gcp:
      project-id: lofty-root-378503

bigquery:
  application-default:
    project-id: ${spring.cloud.gcp.project-id}
    dataset: test_dataset_integration
    table: test_table_integration
  service-account:
    project-id: ${bigquery.application-default.project-id}
    dataset: ${bigquery.application-default.dataset}
    table: ${bigquery.application-default.table}
  uri:
    queries: https://bigquery.googleapis.com/bigquery/v2/projects/${bigquery.application-default.project-id}/queries

gcp:
  service-account: tekton-pipeline@lofty-root-378503.iam.gserviceaccount.com