name: Java CI with Gradle

on:
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'adopt'

      - name: Setup Google Cloud SDK # Setup Google Cloud SDK (skip if already installed in the environment)
        run: |
          if ! gcloud --version; then
            curl -sSL https://sdk.cloud.google.com | bash
          fi
        env:
          GCLOUD_SERVICE_KEY: ${{ secrets.GCLOUD_SERVICE_KEY }}

      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v0.5.0
        with:
          credentials_json: ${{ secrets.GCLOUD_SERVICE_KEY }}

      - name: Grant execute permission for gradlew
        run: chmod +x ./gradlew

      - name: Build with Gradle
        env:
          GCLOUD_SERVICE_KEY: ${{ secrets.GCLOUD_SERVICE_KEY }}
        run: |
          echo "$GCLOUD_SERVICE_KEY" | tr -d '\r' > gcloud-service-key.json
          ./gradlew clean build -DAPP_PROFILE=integration -DGCP_ACCESS_TOKEN=$(gcloud auth print-access-token) -DGCP_SA_KEY_PATH="$PWD/gcloud-service-key.json" -DGOOGLE_APPLICATION_CREDENTIALS="$PWD/gcloud-service-key.json"
