name: Java CI with Gradle

on:
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'adopt'

      # Setup Google Cloud SDK (skip if already installed in the environment)
      - name: Setup Google Cloud SDK
        run: |
          if ! gcloud --version; then
            curl -sSL https://sdk.cloud.google.com | bash
          fi
        env:
          GCLOUD_SERVICE_KEY: ${{ secrets.GCLOUD_SERVICE_KEY }}

      - name: Authenticate with Google Cloud
        env:
          GCLOUD_SERVICE_KEY: ${{ secrets.GCLOUD_SERVICE_KEY }}
        run: |
          echo "$GCLOUD_SERVICE_KEY" | tr -d '\r' > gcloud-service-key.json
          gcloud auth activate-service-account --key-file=gcloud-service-key.json

      # Use GCP_ACCESS_TOKEN as needed for your tasks
      # For example, set it as an environment variable for other steps or use it directly

      - name: Grant execute permission for gradlew
        run: chmod +x ./gradlew

      - name: Build with Gradle
        run: ./gradlew clean build -DPROFILE=integration -DGCP_ACCESS_TOKEN="$GCP_ACCESS_TOKEN"
